// app/01/game/components/ScoreBoard.tsx
import {
  PlayerState,
  calculatePPD,
  calculateAverage,
  getCheckoutSuggestion,
  isCheckoutScore,
} from "@/services/zeroone";
import { Segment, SegmentSection } from "@/services/boardinfo";

interface ScoreBoardProps {
  players: PlayerState[];
  currentPlayerIndex: number;
  gameFinished: boolean;
  currentTurnHits?: Segment[];
  dartsThrown?: number;
}

export function ScoreBoard({
  players,
  currentPlayerIndex,
  gameFinished,
  currentTurnHits = [],
  dartsThrown = 0,
}: ScoreBoardProps) {
  const currentPlayer = players[currentPlayerIndex];
  const otherPlayers = players.filter((_, idx) => idx !== currentPlayerIndex);

  const checkoutSuggestion = currentPlayer
    ? getCheckoutSuggestion(currentPlayer.currentScore)
    : null;
  const onCheckout = currentPlayer
    ? isCheckoutScore(currentPlayer.currentScore)
    : false;

  const ppd = currentPlayer ? calculatePPD(currentPlayer) : 0;
  const avg = currentPlayer ? calculateAverage(currentPlayer) : 0;

  /** Format a dart hit segment for display (e.g. "T20", "D15", "25", "Miss") */
  const formatDartHit = (segment: Segment): string => {
    return segment.ShortName;
  };

  /** True if a dart slot has been thrown */
  const getDartSlotHit = (slotIndex: number): Segment | null => {
    return currentTurnHits[slotIndex] ?? null;
  };

  const isMiss = (segment: Segment) =>
    segment.Section === SegmentSection.Other && segment.Value === 0;

  return (
    <div className="h-full flex flex-col gap-3 overflow-hidden">
      {/* ── Main layout: score plate + stats ── */}
      <div className="flex-1 grid grid-cols-1 lg:grid-cols-3 gap-3 min-h-0">

        {/* ── LEFT: Score Plate (current player) ── */}
        <div
          className="lg:col-span-2 rounded-xl shadow-2xl flex flex-col overflow-hidden border relative"
          style={{
            backgroundColor: 'var(--hud-surface-container-highest)',
            borderColor: 'rgba(69, 70, 77, 0.10)',
          }}
        >
          {/* Decorative glow */}
          <div
            className="absolute -top-10 -right-10 w-40 h-40 rounded-full blur-3xl pointer-events-none"
            style={{ backgroundColor: 'rgba(255, 185, 95, 0.05)' }}
          />

          <div className="flex-1 flex flex-col items-center justify-center px-6 py-8 text-center gap-4">
            {/* Remaining label */}
            <span
              className="text-xs uppercase tracking-[0.2em] font-label font-semibold"
              style={{ color: 'var(--hud-tertiary)' }}
            >
              {"Remaining"}
            </span>

            {/* Big score */}
            {!gameFinished && currentPlayer && (
              <div
                className="font-headline font-extrabold leading-none tracking-tighter"
                style={{
                  fontSize: 'clamp(5rem, 16vw, 9rem)',
                  color: currentPlayer.currentScore === 0
                    ? 'var(--hud-secondary)'
                    : onCheckout
                    ? 'var(--hud-secondary)'
                    : 'var(--hud-primary)',
                }}
                data-testid={`scoreboard-player-${currentPlayer.player.name}`}
              >
                {currentPlayer.currentScore}
              </div>
            )}

            {/* Dart slots */}
            <div className="flex justify-center items-center gap-3 mt-2">
              {[0, 1, 2].map((slotIdx) => {
                const hit = getDartSlotHit(slotIdx);
                const thrown = slotIdx < dartsThrown;
                const isActive = slotIdx === dartsThrown && !gameFinished;

                return (
                  <div
                    key={slotIdx}
                    className="px-4 py-2.5 rounded-lg flex flex-col items-center gap-0.5 min-w-[72px] border transition-all"
                    style={{
                      backgroundColor: isActive
                        ? 'rgba(255, 185, 95, 0.08)'
                        : 'var(--hud-surface-container-low)',
                      borderColor: isActive
                        ? 'rgba(255, 185, 95, 0.3)'
                        : 'rgba(69, 70, 77, 0.10)',
                    }}
                  >
                    <span
                      className="text-[10px] font-semibold uppercase tracking-wider"
                      style={{ color: 'var(--hud-on-tertiary-container)' }}
                    >
                      {`Dart ${slotIdx + 1}`}
                    </span>
                    <span
                      className="text-lg font-headline font-bold"
                      style={{
                        color: !thrown
                          ? 'var(--hud-surface-container-highest)'
                          : hit && isMiss(hit)
                          ? 'var(--hud-error)'
                          : 'var(--hud-secondary)',
                      }}
                    >
                      {thrown && hit ? formatDartHit(hit) : "—"}
                    </span>
                  </div>
                );
              })}
            </div>

            {/* Checkout suggestion */}
            {onCheckout && checkoutSuggestion && !gameFinished && (
              <div
                className="w-full max-w-sm mt-2 px-5 py-3 rounded-lg border flex items-center justify-between gap-3"
                style={{
                  backgroundColor: 'var(--hud-surface-container-low)',
                  borderColor: 'rgba(68, 226, 205, 0.15)',
                }}
              >
                <div>
                  <p
                    className="text-[10px] font-semibold uppercase tracking-widest mb-0.5"
                    style={{ color: 'rgba(185, 200, 222, 0.6)' }}
                  >
                    {"Suggested Checkout"}
                  </p>
                  <p
                    className="text-base font-headline font-bold"
                    style={{ color: 'var(--hud-on-surface)' }}
                  >
                    {checkoutSuggestion}
                  </p>
                </div>
                <div
                  className="w-10 h-10 rounded-full flex items-center justify-center flex-shrink-0 text-lg"
                  style={{
                    backgroundColor: 'rgba(68, 226, 205, 0.1)',
                    color: 'var(--hud-secondary)',
                  }}
                >
                  ⊙
                </div>
              </div>
            )}
          </div>
        </div>

        {/* ── RIGHT: Session Stats + other players ── */}
        <div className="lg:col-span-1 flex flex-col gap-3 min-h-0 overflow-auto">

          {/* Session Stats card */}
          {currentPlayer && (
            <div
              className="rounded-xl p-5 border flex flex-col gap-4"
              style={{
                backgroundColor: 'var(--hud-surface-container-low)',
                borderColor: 'rgba(69, 70, 77, 0.05)',
              }}
            >
              <h3
                className="font-headline font-bold text-base flex items-center gap-2"
                style={{ color: 'var(--hud-on-surface)' }}
              >
                <span style={{ color: 'var(--hud-primary)' }}>▮</span>
                {currentPlayer.player.name}
              </h3>

              <div className="space-y-3">
                {/* Average */}
                <div className="flex justify-between items-end">
                  <div>
                    <p
                      className="text-[10px] font-bold uppercase tracking-widest"
                      style={{ color: 'rgba(185, 200, 222, 0.5)' }}
                    >
                      {"Average"}
                    </p>
                    <p
                      className="text-2xl font-headline font-extrabold"
                      style={{ color: 'var(--hud-on-surface)' }}
                    >
                      {avg.toFixed(1)}
                    </p>
                  </div>
                </div>

                {/* PPD */}
                <div className="flex justify-between items-end">
                  <div>
                    <p
                      className="text-[10px] font-bold uppercase tracking-widest"
                      style={{ color: 'rgba(185, 200, 222, 0.5)' }}
                    >
                      PPD
                    </p>
                    <p
                      className="text-2xl font-headline font-extrabold"
                      style={{ color: 'var(--hud-on-surface)' }}
                    >
                      {ppd.toFixed(1)}
                    </p>
                  </div>
                  <div className="h-1.5 w-14 rounded-full overflow-hidden mb-2"
                    style={{ backgroundColor: 'var(--hud-surface-container)' }}
                  >
                    <div
                      className="h-full rounded-full"
                      style={{
                        width: `${Math.min(100, (ppd / 60) * 100)}%`,
                        backgroundColor: 'var(--hud-primary)',
                      }}
                    />
                  </div>
                </div>

                {/* Total Darts */}
                <div
                  className="pt-3 border-t flex justify-between items-center"
                  style={{ borderColor: 'rgba(69, 70, 77, 0.10)' }}
                >
                  <div>
                    <p
                      className="text-[10px] font-bold uppercase tracking-widest"
                      style={{ color: 'rgba(185, 200, 222, 0.5)' }}
                    >
                      {"Darts"}
                    </p>
                    <p
                      className="text-lg font-headline font-bold"
                      style={{ color: 'var(--hud-on-surface)' }}
                    >
                      {currentPlayer.dartsThrown}
                    </p>
                  </div>
                  {currentPlayer.busts > 0 && (
                    <div
                      className="flex items-center gap-1 text-sm"
                      style={{ color: 'var(--hud-error)' }}
                    >
                      <span>💥</span>
                      <span className="font-medium">{currentPlayer.busts}</span>
                    </div>
                  )}
                </div>
              </div>
            </div>
          )}

          {/* Other players compact cards */}
          {otherPlayers.length > 0 && (
            <div className="flex flex-col gap-2">
              {otherPlayers.map((playerState) => {
                const isFinished = playerState.currentScore === 0;
                return (
                  <div
                    key={playerState.player.id}
                    data-testid={`scoreboard-player-${playerState.player.name}`}
                    className="px-4 py-3 rounded-xl border flex items-center justify-between"
                    style={{
                      backgroundColor: isFinished
                        ? 'rgba(68, 226, 205, 0.08)'
                        : 'var(--hud-surface-container)',
                      borderColor: isFinished
                        ? 'rgba(68, 226, 205, 0.25)'
                        : 'rgba(69, 70, 77, 0.10)',
                    }}
                  >
                    <div className="flex items-center gap-2">
                      {isFinished && (
                        <span style={{ color: 'var(--hud-secondary)' }}>✓</span>
                      )}
                      <span
                        className="font-headline font-bold text-sm"
                        style={{
                          color: isFinished
                            ? 'var(--hud-secondary)'
                            : 'var(--hud-on-surface)',
                        }}
                      >
                        {playerState.player.name}
                      </span>
                    </div>
                    <span
                      className="text-2xl font-headline font-extrabold"
                      style={{
                        color: isFinished
                          ? 'var(--hud-secondary)'
                          : 'var(--hud-on-surface-variant)',
                      }}
                    >
                      {playerState.currentScore}
                    </span>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// src/components/01/ScoreBoard.svelte
<script lang="ts">
  import {
    type PlayerState,
    calculatePPD,
    calculateAverage,
    getCheckoutSuggestion,
    isCheckoutScore,
  } from '@/services/zeroone';
  import { type Segment, SegmentSection } from '@/services/boardinfo';

  interface Props {
    players: PlayerState[];
    currentPlayerIndex: number;
    gameFinished: boolean;
    currentTurnHits?: Segment[];
    dartsThrown?: number;
    currentRound?: number;
    maxRounds?: number;
    hasHistory?: boolean;
    onUndo?: () => void;
    onNextPlayer?: () => void;
  }

  let {
    players,
    currentPlayerIndex,
    gameFinished,
    currentTurnHits = [],
    dartsThrown = 0,
    currentRound = 1,
    maxRounds = 0,
    hasHistory = false,
    onUndo,
    onNextPlayer,
  }: Props = $props();

  let currentPlayer = $derived(players[currentPlayerIndex]);
  let otherPlayers = $derived(
    players
      .map((p, idx) => ({ ...p, originalIndex: idx }))
      .filter((_, idx) => idx !== currentPlayerIndex)
  );

  let checkoutSuggestion = $derived(
    currentPlayer ? getCheckoutSuggestion(currentPlayer.currentScore) : null
  );
  let onCheckout = $derived(
    currentPlayer ? isCheckoutScore(currentPlayer.currentScore) : false
  );

  let avg = $derived(currentPlayer ? calculateAverage(currentPlayer) : 0);

  /** Compute last turn score from turn hits */
  let lastTurnScore = $derived(
    currentTurnHits.reduce((sum, hit) => sum + hit.Value, 0)
  );

  /** Parse checkout suggestion into individual dart labels */
  function parseCheckoutDarts(suggestion: string): { label: string; isDouble: boolean }[] {
    return suggestion.split(',').map((s) => {
      const trimmed = s.trim();
      return {
        label: trimmed,
        isDouble: trimmed.startsWith('D') || trimmed === 'Bull',
      };
    });
  }

  /** Get next player index for "Up Next" display */
  function getNextPlayerIndex(): number {
    return (currentPlayerIndex + 1) % players.length;
  }
</script>

<div class="h-full flex flex-col md:flex-row gap-8 lg:gap-12 items-center overflow-hidden px-4 lg:px-8">

  <!-- LEFT: Active Player Focus (Expanded) -->
  <section class="flex-[2] flex flex-col justify-center items-center text-center gap-4 min-h-0">

    <!-- Current Player Label + Name -->
    <div class="flex flex-col items-center">
      <span
        class="text-[11px] font-bold tracking-[0.3em] uppercase mb-2"
        style="color: var(--hud-primary); opacity: 0.6;"
      >
        Current Player
      </span>
      <h1
        class="text-5xl md:text-7xl lg:text-8xl font-black tracking-tighter font-headline"
        style="color: var(--hud-on-surface);"
      >
        {#if currentPlayer}
          {currentPlayer.player.name.toUpperCase()}
        {/if}
      </h1>
    </div>

    <!-- Massive Central Score -->
    {#if !gameFinished && currentPlayer}
      <div class="relative py-2 md:py-4">
        <div
          class="font-black leading-none tracking-tighter text-transparent amber-gradient text-glow"
          style="font-size: clamp(8rem, 22vw, 20rem);"
          data-testid={`scoreboard-player-${currentPlayer.player.name}`}
        >
          {currentPlayer.currentScore}
        </div>

        <!-- Checkout Suggestion (floating pill) -->
        {#if onCheckout && checkoutSuggestion}
          {@const darts = parseCheckoutDarts(checkoutSuggestion)}
          <div
            class="absolute -bottom-4 md:-bottom-6 left-1/2 -translate-x-1/2 glass-panel px-6 md:px-10 py-3 md:py-4 rounded-full flex items-center gap-4 md:gap-6 shadow-2xl border"
            style="border-color: rgba(69, 70, 77, 0.15);"
          >
            <span
              class="text-[10px] md:text-xs font-bold tracking-[0.2em] uppercase"
              style="color: var(--hud-primary); opacity: 0.6;"
            >
              Target:
            </span>
            <div class="flex gap-3 md:gap-4">
              {#each darts as dart}
                <span
                  class="text-lg md:text-2xl font-black"
                  style="color: {dart.isDouble ? 'var(--hud-primary)' : 'var(--hud-on-surface)'};"
                >
                  {dart.label}
                </span>
              {/each}
            </div>
          </div>
        {/if}
      </div>
    {/if}

    <!-- Stats Row: Average, Darts, Last Turn -->
    {#if currentPlayer}
      <div class="grid grid-cols-3 gap-12 md:gap-20 pt-10 md:pt-16">
        <div class="flex flex-col">
          <span
            class="text-[10px] md:text-[11px] font-bold tracking-[0.3em] uppercase"
            style="color: rgba(148, 163, 184, 0.6);"
          >
            Average
          </span>
          <span
            class="text-2xl md:text-4xl font-bold font-headline mt-1"
            style="color: var(--hud-on-surface);"
          >
            {avg.toFixed(1)}
          </span>
        </div>
        <div class="flex flex-col">
          <span
            class="text-[10px] md:text-[11px] font-bold tracking-[0.3em] uppercase"
            style="color: rgba(148, 163, 184, 0.6);"
          >
            Darts
          </span>
          <span
            class="text-2xl md:text-4xl font-bold font-headline mt-1"
            style="color: var(--hud-on-surface);"
          >
            {currentPlayer.dartsThrown}
          </span>
        </div>
        <div class="flex flex-col">
          <span
            class="text-[10px] md:text-[11px] font-bold tracking-[0.3em] uppercase"
            style="color: rgba(148, 163, 184, 0.6);"
          >
            Last Turn
          </span>
          <span
            class="text-2xl md:text-4xl font-bold font-headline mt-1"
            style="color: var(--hud-on-surface);"
          >
            {lastTurnScore}
          </span>
        </div>
      </div>
    {/if}

    <!-- Undo / Next Player controls (compact, below stats) -->
    {#if !gameFinished && currentPlayer}
      <div class="flex items-center gap-3 pt-4">
        {#if onUndo}
          <button
            data-testid="undo-button"
            onclick={onUndo}
            disabled={!hasHistory}
            class="px-4 py-2 rounded-lg font-bold text-sm transition-all"
            style="background-color: {!hasHistory
              ? 'var(--hud-surface-container-high)'
              : 'var(--hud-primary)'}; color: {!hasHistory
              ? 'var(--hud-on-tertiary-container)'
              : 'var(--hud-on-primary)'}; cursor: {!hasHistory ? 'not-allowed' : 'pointer'}; opacity: {!hasHistory ? 0.5 : 1};"
            title="Undo last move"
          >
            &#x21B6; Undo
          </button>
        {/if}
        {#if onNextPlayer}
          <button
            data-testid="next-player-button"
            onclick={onNextPlayer}
            class="px-4 py-2 rounded-lg font-bold text-sm transition-all"
            style="background-color: var(--hud-error-container); color: var(--hud-on-error-container);"
            title="End turn and pass to next player"
          >
            Next Player
          </button>
        {/if}
      </div>
    {/if}
  </section>

  <!-- RIGHT: Player Standings & Match Info -->
  <section class="flex-1 flex flex-col gap-4 md:gap-6 self-center w-full max-w-md min-h-0">

    <!-- Header for Standings -->
    <div class="flex items-center justify-between px-2">
      <span
        class="text-xs font-bold tracking-[0.2em] uppercase"
        style="color: rgba(148, 163, 184, 0.6);"
      >
        Standings
      </span>
      <div class="flex items-center gap-2">
        <span
          class="text-[10px] font-bold tracking-[0.15em] uppercase"
          style="color: var(--hud-primary);"
        >
          Round {currentRound}{#if maxRounds > 0} / {maxRounds}{/if}
        </span>
      </div>
    </div>

    <!-- Player Cards (Vertical List) -->
    <div class="flex flex-col gap-3 overflow-y-auto">
      {#each otherPlayers as playerState, idx (playerState.player.id)}
        {@const isNext = playerState.originalIndex === getNextPlayerIndex()}
        {@const isFinished = playerState.currentScore === 0}
        <div
          data-testid={`scoreboard-player-${playerState.player.name}`}
          class="p-5 md:p-6 lg:p-8 rounded-2xl flex flex-col gap-2 transition-all duration-300 relative overflow-hidden group"
          style="background-color: {isNext
            ? 'var(--hud-surface-container-high)'
            : isFinished
              ? 'rgba(68, 226, 205, 0.08)'
              : 'rgba(19, 27, 46, 0.5)'}; border: 1px solid {isNext
            ? 'rgba(255, 185, 95, 0.2)'
            : isFinished
              ? 'rgba(68, 226, 205, 0.25)'
              : 'transparent'}; {isNext
            ? 'box-shadow: 0 4px 24px rgba(255, 185, 95, 0.08);'
            : ''} {!isNext && !isFinished ? 'opacity: 0.5;' : ''}"
        >
          <!-- Up Next badge -->
          {#if isNext}
            <div class="absolute top-0 right-0 p-3 opacity-20 group-hover:opacity-100 transition-opacity">
              <span
                class="text-[10px] font-black uppercase"
                style="color: var(--hud-primary);"
              >
                Up Next
              </span>
            </div>
          {/if}

          <span
            class="text-[10px] font-bold tracking-[0.15em] uppercase"
            style="color: rgba(148, 163, 184, 0.6);"
          >
            Player {String(playerState.originalIndex + 1).padStart(2, '0')}
          </span>
          <div class="flex justify-between items-end">
            <span
              class="text-lg md:text-2xl font-bold font-headline"
              style="color: {isFinished ? 'var(--hud-secondary)' : 'var(--hud-on-surface)'};"
            >
              {playerState.player.name.toUpperCase()}
            </span>
            <span
              class="text-2xl md:text-4xl font-black font-headline"
              style="color: {isFinished ? 'var(--hud-secondary)' : 'var(--hud-on-surface)'};"
            >
              {playerState.currentScore}
            </span>
          </div>
        </div>
      {/each}
    </div>

    <!-- Match Status Footer -->
    <div
      class="mt-2 md:mt-4 p-5 md:p-8 rounded-2xl flex flex-col items-center gap-1 border"
      style="background-color: rgba(6, 14, 32, 0.3); border-color: rgba(69, 70, 77, 0.10);"
    >
      <span
        class="text-[11px] font-bold tracking-[0.3em] uppercase mb-2"
        style="color: rgba(148, 163, 184, 0.6);"
      >
        Match Progress
      </span>
      <div class="flex items-center gap-6 md:gap-8">
        <div class="flex flex-col items-center">
          <span
            class="text-xs font-bold uppercase mb-1"
            style="color: rgba(148, 163, 184, 0.6);"
          >
            Round
          </span>
          <span
            class="text-xl md:text-2xl font-black font-headline"
            style="color: var(--hud-primary);"
          >
            {currentRound}
          </span>
        </div>
        <div
          class="w-px h-8"
          style="background-color: rgba(69, 70, 77, 0.20);"
        ></div>
        <div class="flex flex-col items-center">
          <span
            class="text-xs font-bold uppercase mb-1"
            style="color: rgba(148, 163, 184, 0.6);"
          >
            Darts
          </span>
          <span
            class="text-xl md:text-2xl font-black font-headline"
            style="color: var(--hud-on-surface);"
          >
            {dartsThrown} / 3
          </span>
        </div>
      </div>
      <!-- Progress bar -->
      {#if maxRounds > 0}
        <div
          class="mt-4 w-full h-1.5 rounded-full overflow-hidden"
          style="background-color: var(--hud-surface-container-highest);"
        >
          <div
            class="h-full rounded-full transition-all duration-500"
            style="width: {Math.min(100, (currentRound / maxRounds) * 100)}%; background-color: var(--hud-primary); box-shadow: 0 0 10px rgba(255, 185, 95, 0.5);"
          ></div>
        </div>
      {/if}
    </div>
  </section>
</div>
